/**
 * @param { import("knex").Knex } knex
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("tourist").del();
  await knex("owner").del();
  await knex("business").del();
  await knex("barangay").del();
  await knex("municipality").del();
  await knex("province").del();
  await knex("category").del();
  await knex("type").del();

  // Inserts seed entries
  await knex("province").insert([
    { id: 1, province: "Abra" },
    { id: 2, province: "Agusan del Norte" },
    { id: 3, province: "Agusan del Sur" },
    { id: 4, province: "Aklan" },
    { id: 5, province: "Albay" },
    { id: 6, province: "Antique" },
    { id: 7, province: "Apayao" },
    { id: 8, province: "Aurora" },
    { id: 9, province: "Basilan" },
    { id: 10, province: "Bataan" },
    { id: 11, province: "Batanes" },
    { id: 12, province: "Batangas" },
    { id: 13, province: "Benguet" },
    { id: 14, province: "Biliran" },
    { id: 15, province: "Bohol" },
    { id: 16, province: "Bukidnon" },
    { id: 17, province: "Bulacan" },
    { id: 18, province: "Cagayan" },
    { id: 19, province: "Camarines Norte" },
    { id: 20, province: "Camarines Sur" },
    { id: 21, province: "Camiguin" },
    { id: 22, province: "Capiz" },
    { id: 23, province: "Catanduanes" },
    { id: 24, province: "Cavite" },
    { id: 25, province: "Cebu" },
    { id: 26, province: "Compostela Valley" },
    { id: 27, province: "Cotabato" },
    { id: 28, province: "Davao del Norte" },
    { id: 29, province: "Davao del Sur" },
    { id: 30, province: "Davao Occidental" },
    { id: 31, province: "Davao Oriental" },
    { id: 32, province: "Dinagat Islands" },
    { id: 33, province: "Eastern Samar" },
    { id: 34, province: "Guimaras" },
    { id: 35, province: "Ifugao" },
    { id: 36, province: "Ilocos Norte" },
    { id: 37, province: "Ilocos Sur" },
    { id: 38, province: "Iloilo" },
    { id: 39, province: "Isabela" },
    { id: 40, province: "Kalinga" },
    { id: 41, province: "La Union" },
    { id: 42, province: "Laguna" },
    { id: 43, province: "Lanao del Norte" },
    { id: 44, province: "Lanao del Sur" },
    { id: 45, province: "Leyte" },
    { id: 46, province: "Maguindanao" },
    { id: 47, province: "Marinduque" },
    { id: 48, province: "Masbate" },
    { id: 49, province: "Misamis Occidental" },
    { id: 50, province: "Misamis Oriental" },
    { id: 51, province: "Mountain Province" },
    { id: 52, province: "Negros Occidental" },
    { id: 53, province: "Negros Oriental" },
    { id: 54, province: "Northern Samar" },
    { id: 55, province: "Nueva Ecija" },
    { id: 56, province: "Nueva Vizcaya" },
    { id: 57, province: "Occidental Mindoro" },
    { id: 58, province: "Oriental Mindoro" },
    { id: 59, province: "Palawan" },
    { id: 60, province: "Pampanga" },
    { id: 61, province: "Pangasinan" },
    { id: 62, province: "Quezon" },
    { id: 63, province: "Quirino" },
    { id: 64, province: "Rizal" },
    { id: 65, province: "Romblon" },
    { id: 66, province: "Samar" },
    { id: 67, province: "Sarangani" },
    { id: 68, province: "Siquijor" },
    { id: 69, province: "Sorsogon" },
    { id: 70, province: "South Cotabato" },
    { id: 71, province: "Southern Leyte" },
    { id: 72, province: "Sultan Kudarat" },
    { id: 73, province: "Sulu" },
    { id: 74, province: "Surigao del Norte" },
    { id: 75, province: "Surigao del Sur" },
    { id: 76, province: "Tarlac" },
    { id: 77, province: "Tawi-Tawi" },
    { id: 78, province: "Zambales" },
    { id: 79, province: "Zamboanga del Norte" },
    { id: 80, province: "Zamboanga del Sur" },
    { id: 81, province: "Zamboanga Sibugay" },
    { id: 82, province: "Davao de Oro" },
  ]);
}
